name: 🐛 Signaler un bug
description: Signalez un bug pour nous aider à améliorer Papillon
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Étapes à reproduire
      description: "Étapes pour reproduire le bug :"
      placeholder: |
        1. [ex: Etape 1]
        2. [ex: Etape 1]
      value: |
        1. 
        2.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comportement attendu
      description: Une description claire et concise de ce que vous attendiez.
    validations:
      required: true
  - type: input
    attributes:
      label: Appareil
      placeholder: iPhone 13, Samsung Galaxy S23...
    validations:
      required: true
  - type: input
    attributes:
      label: Version du système d`exploitation
      placeholder: iOS 18, Android 14...
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      placeholder: "7.0.1-beta"
      value: "7.0.1-beta"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Environnement
      options:
        - Application native Android
        - Application native iOS
        - Prébuild de développement (iOS/Android)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Source de l'application
      options:
        - Stores (Play Store / App Store)
        - Github
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Service scolaire
      options:
        - 🦋 Pronote
        - 🟦 EcoleDirecte
        - 🟡 Skolengo
        - 🔴 Turboself
        - 🟣 ARD-GEC
        - ⭕ Autre
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Captures d'écran / vidéo"
      description: "Si possible, ajoutez des captures d'écran pour aider à expliquer votre problème."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Contexte supplémentaire
      description: Des liens ? Des références ? Tout ce qui peut nous donner plus de détails sur le problème que vous rencontrez !
    validations:
      required: false
